import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsEnum, IsNumber, IsOptional, IsArray, IsUrl, MaxLength } from 'class-validator';
import { PartialType } from '@nestjs/swagger';
import { CreateArticleDto } from './create-article.dto';

export class UpdateArticleDto extends PartialType(CreateArticleDto) {
  @ApiProperty({ example: 'The Future of AI in Healthcare', required: false })
  @IsString()
  @MaxLength(200)
  @IsOptional()
  title?: string;

  @ApiProperty({
    enum: ['AI', 'finance', 'economics', 'technology', 'sociology'],
    required: false,
  })
  @IsEnum(['AI', 'finance', 'economics', 'technology', 'sociology'])
  @IsOptional()
  domain?: string;

  @ApiProperty({
    enum: ['beginner', 'intermediate', 'advanced'],
    required: false,
  })
  @IsEnum(['beginner', 'intermediate', 'advanced'])
  @IsOptional()
  difficulty?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  content?: string;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  wordCount?: number;

  @ApiProperty({
    example: { coreQuestion: '...', mainConclusion: '...', argumentStructure: ['...'] },
    required: false,
    description: 'Reading map generated by AI',
  })
  @IsOptional()
  readingMap?: {
    coreQuestion: string;
    mainConclusion: string;
    argumentStructure: string[];
  };

  @ApiProperty({
    example: [{ paragraphIndex: 0, text: '...', role: 'argument', keySentences: ['...'] }],
    required: false,
    description: 'Key paragraphs analysis',
  })
  @IsOptional()
  keyParagraphs?: {
    paragraphIndex: number;
    text: string;
    role: 'definition' | 'argument' | 'refutation';
    keySentences: string[];
  }[];

  @ApiProperty({
    example: [{ expression: '...', explanation: '...', transferable: true }],
    required: false,
    description: 'Language breakdown for reasoning expressions',
  })
  @IsOptional()
  languageBreakdown?: {
    expression: string;
    explanation: string;
    transferable: boolean;
  }[];

  @ApiProperty({
    example: [{ question: '...', sampleAnswer: '...' }],
    required: false,
    description: 'Understanding check questions',
  })
  @IsOptional()
  understandingQuestions?: {
    question: string;
    sampleAnswer: string;
  }[];

  @ApiProperty({ required: false })
  @IsOptional()
  scheduledFor?: Date;

  @ApiProperty({ required: false })
  @IsOptional()
  publishedAt?: Date;
}
